/**
 * Blueprint executor — executa um blueprint localmente.
 *
 * Semântica adaptada do Devin:
 * - `initialize` roda uma vez, em ~ ou workdir
 * - `maintenance` roda a cada build, em workdir
 * - `knowledge` NÃO é executado — apenas retornado como contexto
 * - `post-build` roda após initialize+maintenance (org/enterprise only)
 * - `clone` faz git clone com overrides (repo only)
 *
 * Variáveis de ambiente:
 * - $MCP_ENVRC: arquivo para propagar env entre steps (como $ENVRC do Devin)
 * - Secrets: injetados como env vars antes de cada step
 * - $FILE_*: paths para arquivos anexados
 *
 * NÃO usa Devin. Roda localmente ou em CI.
 */

import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir, appendFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import type {
  Blueprint,
  BlueprintContext,
  BlueprintExecutionResult,
  Step,
  StepResult,
  KnowledgeEntry,
} from './types.js';

const execFileAsync = promisify(execFile);

const STEP_TIMEOUT_MS = 60 * 60 * 1000; // 1h, igual ao Devin

export class BlueprintExecutor {
  constructor(private ctx: BlueprintContext) {}

  /**
   * Executa um blueprint completo.
   */
  async execute(blueprint: Blueprint): Promise<BlueprintExecutionResult> {
    const startedAt = Date.now();
    const steps: StepResult[] = [];

    // 0. Inicializa ENVRC (arquivo vazio para source funcionar desde step 1)
    await mkdir(join(this.ctx.envrc, '..'), { recursive: true });
    if (!existsSync(this.ctx.envrc)) {
      await appendFile(this.ctx.envrc, '# MCP_ENVRC — auto-generated by BlueprintExecutor\n');
    }

    // 1. clone (repo only)
    if (blueprint.clone && this.ctx.scope === 'repository') {
      const r = await this.executeClone(blueprint);
      steps.push(r);
      if (!r.ok) return this.finish(blueprint, steps, startedAt);
    }

    // 2. initialize
    if (blueprint.initialize) {
      const initSteps = Array.isArray(blueprint.initialize)
        ? blueprint.initialize
        : [{ run: blueprint.initialize } as Step];
      for (const step of initSteps) {
        const r = await this.executeStep(step, 'initialize');
        steps.push(r);
        if (!r.ok) return this.finish(blueprint, steps, startedAt);
      }
    }

    // 3. maintenance
    if (blueprint.maintenance) {
      const maintSteps = Array.isArray(blueprint.maintenance)
        ? blueprint.maintenance
        : [{ run: blueprint.maintenance } as Step];
      for (const step of maintSteps) {
        const r = await this.executeStep(step, 'maintenance');
        steps.push(r);
        if (!r.ok) return this.finish(blueprint, steps, startedAt);
      }
    }

    // 4. post-build (org/enterprise only)
    if (blueprint.postBuild && this.ctx.scope !== 'repository') {
      const pbSteps = Array.isArray(blueprint.postBuild)
        ? blueprint.postBuild
        : [{ run: blueprint.postBuild } as Step];
      for (const step of pbSteps) {
        const r = await this.executeStep(step, 'post-build');
        steps.push(r);
        if (!r.ok) return this.finish(blueprint, steps, startedAt);
      }
    } else if (blueprint.postBuild && this.ctx.scope === 'repository') {
      this.ctx.logger.warn('post-build ignored in repository-level blueprint (org/enterprise only)');
    }

    return this.finish(blueprint, steps, startedAt);
  }

  /**
   * Extrai knowledge entries (não executadas).
   */
  extractKnowledge(blueprint: Blueprint): KnowledgeEntry[] {
    return blueprint.knowledge ?? [];
  }

  // ==========================================================================
  // Step execution
  // ==========================================================================

  private async executeStep(step: Step, phase: string): Promise<StepResult> {
    const name = step.name ?? `${phase}-step`;
    const startedAt = Date.now();

    this.ctx.logger.info(`[${phase}] ${name}`);

    try {
      if ('run' in step) {
        return await this.executeRun(step, name, startedAt);
      } else if ('uses' in step) {
        return await this.executeUses(step, name, startedAt);
      }
      throw new Error('step must have run or uses');
    } catch (err) {
      const durationMs = Date.now() - startedAt;
      return {
        name,
        ok: false,
        stderr: (err as Error).message,
        exitCode: -1,
        durationMs,
      };
    }
  }

  private async executeRun(
    step: Extract<Step, { run: string }>,
    name: string,
    startedAt: number,
  ): Promise<StepResult> {
    // montar env: global + step env + secrets + ENVRC sourcing
    const env: Record<string, string> = {
      ...process.env as Record<string, string>,
      ...(this.ctx.scope === 'organization' ? {} : {}),
      ...step.env,
      MCP_ENVRC: this.ctx.envrc,
    };

    // injetar secrets como env vars
    for (const [k, v] of Object.entries(this.ctx.secrets)) {
      env[k] = v;
    }

    // source $MCP_ENVRC antes de executar (se existir)
    const sourceEnvrc = existsSync(this.ctx.envrc)
      ? `source ${this.ctx.envrc} 2>/dev/null || true; `
      : '';

    const command = `${sourceEnvrc}set -e;\n${step.run}`;
    try {
      const { stdout, stderr } = await execFileAsync('bash', ['-c', command], {
        cwd: this.ctx.workdir,
        env,
        timeout: STEP_TIMEOUT_MS,
        maxBuffer: 10 * 1024 * 1024,
      });
      return {
        name,
        ok: true,
        stdout,
        stderr,
        exitCode: 0,
        durationMs: Date.now() - startedAt,
      };
    } catch (err) {
      const e = err as { stdout?: string; stderr?: string; code?: number | string };
      return {
        name,
        ok: false,
        stdout: e.stdout,
        stderr: e.stderr,
        exitCode: typeof e.code === 'number' ? e.code : -1,
        durationMs: Date.now() - startedAt,
      };
    }
  }

  /**
   * Executa GitHub Action localmente (placeholder — em CI real seria via actions runner).
   * Em modo local, faz download e executa via node.
   */
  private async executeUses(
    step: Extract<Step, { uses: string }>,
    name: string,
    startedAt: number,
  ): Promise<StepResult> {
    // Parser: github.com/<owner>/<repo>/<subpath>?@<ref>
    const match = step.uses.match(/^github\.com\/([^/]+)\/([^/@]+)(\/[^@]+)?@(.+)$/);
    if (!match) {
      return {
        name,
        ok: false,
        stderr: `invalid uses: ${step.uses}`,
        exitCode: -1,
        durationMs: Date.now() - startedAt,
      };
    }
    const [, owner, repo, subpath, ref] = match;
    const actionPath = subpath?.slice(1) ?? '';

    this.ctx.logger.info(`[${name}] action: ${owner}/${repo}@${ref}${actionPath ? '/' + actionPath : ''}`);

    // Em produção: clonar action, instalar deps, executar via node com inputs em stdin
    // Aqui: simulação — logamos o que faria
    const inputs = step.with ?? {};
    const inputJson = JSON.stringify(inputs, null, 2);

    // marcador de que seria executado em CI real
    if (process.env.GITHUB_ACTIONS === 'true') {
      // em CI real, usaria composite action ou action via act
      return {
        name,
        ok: true,
        stdout: `[would run action ${owner}/${repo}@${ref} with inputs:\n${inputJson}\n]`,
        exitCode: 0,
        durationMs: Date.now() - startedAt,
      };
    }

    // modo local: log apenas
    return {
      name,
      ok: true,
      stdout: `[local mode] would run action ${owner}/${repo}@${ref}\ninputs: ${inputJson}`,
      exitCode: 0,
      durationMs: Date.now() - startedAt,
    };
  }

  // ==========================================================================
  // Clone
  // ==========================================================================

  private async executeClone(blueprint: Blueprint): Promise<StepResult> {
    const startedAt = Date.now();
    const c = blueprint.clone!;
    const name = 'clone';

    if (!blueprint.name) {
      return { name, ok: false, stderr: 'blueprint.name required for clone', exitCode: -1, durationMs: 0 };
    }

    const destPath = c.path ?? blueprint.name;
    const fullPath = join(this.ctx.workdir, destPath);
    const _ref = c.ref ?? 'main';
    void _ref;

    const args = ['clone'];
    if (c.depth && c.depth > 0) args.push('--depth', String(c.depth));
    if (c.tags === false) args.push('--no-tags');
    if (c.submodules === true) args.push('--recurse-submodules');
    if (c.submodules === 'recursive') args.push('--recurse-submodules', '--remote-submodules');
    if (c.lfs === false) process.env.GIT_LFS_SKIP_SMUDGE = '1';

    // assume origin URL via env
    const originUrl = this.ctx.secrets.GIT_ORIGIN_URL ?? `https://github.com/${blueprint.name}.git`;
    args.push(originUrl, fullPath);

    // checkout ref após clone
    try {
      const { stdout, stderr } = await execFileAsync('git', args, {
        timeout: STEP_TIMEOUT_MS,
        maxBuffer: 10 * 1024 * 1024,
      });
      // checkout ref
      if (c.ref) {
        await execFileAsync('git', ['-C', fullPath, 'checkout', c.ref]);
      }
      return {
        name,
        ok: true,
        stdout,
        stderr,
        exitCode: 0,
        durationMs: Date.now() - startedAt,
      };
    } catch (err) {
      const e = err as { stderr?: string; code?: number };
      return {
        name,
        ok: false,
        stderr: e.stderr,
        exitCode: typeof e.code === 'number' ? e.code : -1,
        durationMs: Date.now() - startedAt,
      };
    }
  }

  // ==========================================================================
  // Helpers
  // ==========================================================================

  private async finish(
    _blueprint: Blueprint,
    steps: StepResult[],
    startedAt: number,
  ): Promise<BlueprintExecutionResult> {
    void _blueprint;
    const ok = steps.every(s => s.ok);
    return {
      scope: this.ctx.scope,
      steps,
      ok,
      durationMs: Date.now() - startedAt,
      artifacts: ok ? [this.ctx.envrc] : [],
    };
  }

  /**
   * Escreve variável em $MCP_ENVRC para propagar entre steps.
   */
  static async writeEnvrc(envrcPath: string, vars: Record<string, string>): Promise<void> {
    const lines = Object.entries(vars).map(([k, v]) => `export ${k}="${v.replace(/"/g, '\\"')}"\n`);
    await mkdir(join(envrcPath, '..'), { recursive: true });
    await appendFile(envrcPath, lines.join(''));
  }

  /**
   * Cria context para um blueprint local.
   */
  static createContext(opts: {
    scope: 'enterprise' | 'organization' | 'repository';
    workdir: string;
    secrets?: Record<string, string>;
    logger?: BlueprintContext['logger'];
  }): BlueprintContext {
    const envrc = join(opts.workdir, '.mcp', 'envrc.sh');
    return {
      scope: opts.scope,
      workdir: opts.workdir,
      envrc,
      secrets: opts.secrets ?? {},
      logger: opts.logger ?? {
        info: (m, meta) => console.log(`[INFO] ${m}`, meta ?? ''),
        warn: (m, meta) => console.warn(`[WARN] ${m}`, meta ?? ''),
        error: (m, meta) => console.error(`[ERROR] ${m}`, meta ?? ''),
      },
    };
  }
}

/**
 * Helper: cria hash determinístico de um blueprint (para cache/snapshot).
 */
export function hashBlueprint(bp: Blueprint): string {
  const json = JSON.stringify({
    scope: bp.scope,
    name: bp.name,
    initialize: bp.initialize,
    maintenance: bp.maintenance,
    knowledge: bp.knowledge,
    postBuild: bp.postBuild,
    clone: bp.clone,
    env: bp.env,
  });
  return createHash('sha256').update(json).digest('hex');
}

// re-export yaml serialize para uso externo
export { serializeBlueprint } from './parser.js';
