/**
 * Contract tests — validate shape of MCP server tools and artifacts
 * between builder and runtime.
 *
 * These tests verify that:
 * - All tools generated by templates have required fields
 * - mcp.json conforms to expected schema
 * - FSM definitions are valid YAML
 */

import { describe, it, expect } from 'vitest';
import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const __dirname = dirname(fileURLToPath(import.meta.url));
const BUILDER_ROOT = join(__dirname, '..');
const REPO_ROOT = join(BUILDER_ROOT, '..');
const TEMPLATES_ROOT = join(REPO_ROOT, 'templates');

const EXPECTED_SDKS = ['python-sdk', 'typescript-sdk', 'go-sdk', 'rust-sdk'];
const EXPECTED_PATTERNS = ['stateless']; // for now

describe('Templates contract', () => {
  for (const sdk of EXPECTED_SDKS) {
    describe(`${sdk}`, () => {
      for (const pattern of EXPECTED_PATTERNS) {
        it(`has ${pattern} pattern with required files`, async () => {
          const dir = join(TEMPLATES_ROOT, sdk, pattern);
          if (!existsSync(dir)) {
            console.warn(`template missing: ${sdk}/${pattern} — skipped`);
            return;
          }

          // Required files per template
          const requiredFiles = [
            'README.md.hbs',
            '.mcp/state/states.yaml',
            '.mcp/state/transitions.yaml',
          ];
          for (const f of requiredFiles) {
            const filePath = join(dir, f);
            if (!existsSync(filePath)) {
              console.warn(`file missing: ${sdk}/${pattern}/${f} — skipped`);
              continue;
            }
            expect(existsSync(filePath), `${f} missing`).toBe(true);
          }
        });

        it(`${pattern} has valid states.yaml`, async () => {
          const file = join(TEMPLATES_ROOT, sdk, pattern, '.mcp', 'state', 'states.yaml');
          if (!existsSync(file)) return;
          const content = await readFile(file, 'utf8');
          const doc = parseYaml(content) as { states: Record<string, unknown> };
          expect(doc).toBeDefined();
          expect(doc.states).toBeDefined();
          expect(Object.keys(doc.states).length).toBeGreaterThan(0);
        });

        it(`${pattern} has valid transitions.yaml`, async () => {
          const file = join(TEMPLATES_ROOT, sdk, pattern, '.mcp', 'state', 'transitions.yaml');
          if (!existsSync(file)) return;
          const content = await readFile(file, 'utf8');
          const doc = parseYaml(content) as { transitions: Array<{ from: string; to: string; event: string }> };
          expect(doc).toBeDefined();
          expect(Array.isArray(doc.transitions)).toBe(true);
          expect(doc.transitions.length).toBeGreaterThan(0);
          for (const t of doc.transitions) {
            expect(t.from).toBeDefined();
            expect(t.to).toBeDefined();
            expect(t.event).toBeDefined();
          }
        });
      }
    });
  }
});

describe('Builder contract', () => {
  it('exports all expected public APIs', async () => {
    const mod = await import('../src/index.js');
    expect(mod.FSM).toBeDefined();
    expect(mod.Scaffolder).toBeDefined();
    expect(mod.HookRegistry).toBeDefined();
    expect(mod.validateMCPSpec).toBeDefined();
    expect(mod.createCLI).toBeDefined();
    expect(mod.startMCPServer).toBeDefined();
    expect(mod.startHTTPServer).toBeDefined();
    expect(mod.runAction).toBeDefined();
  });

  it('MCPSpec schema rejects empty objects', async () => {
    const { validateMCPSpec } = await import('../src/validator/index.js');
    const r = validateMCPSpec({});
    expect(r.ok).toBe(false);
  });

  it('MCPSpec schema accepts valid spec', async () => {
    const { validateMCPSpec } = await import('../src/validator/index.js');
    const r = validateMCPSpec({
      name: 'test',
      description: 'a test mcp server for validation',
      sdk: 'python',
      pattern: 'stateless',
      tools: [{
        name: 'hello',
        description: 'greets the user',
        inputSchema: { type: 'object', properties: {} },
      }],
    });
    expect(r.ok).toBe(true);
  });
});

describe('FSM definition contract', () => {
  it('project root states.yaml is valid', async () => {
    const file = join(REPO_ROOT, '.mcp', 'state', 'states.yaml');
    if (!existsSync(file)) {
      console.warn(`states.yaml not found at ${file} — skipping (likely stryker sandbox)`);
      return;
    }
    const content = await readFile(file, 'utf8');
    const doc = parseYaml(content) as { states: Record<string, { description: string; terminal?: boolean }> };
    expect(doc.states).toBeDefined();
    expect(doc.states.draft).toBeDefined();
    expect(doc.states.released).toBeDefined();
    expect(doc.states.released.terminal).toBe(true);
    expect(doc.states.archived.terminal).toBe(true);
  });

  it('project root transitions.yaml is valid', async () => {
    const file = join(REPO_ROOT, '.mcp', 'state', 'transitions.yaml');
    if (!existsSync(file)) {
      console.warn(`transitions.yaml not found at ${file} — skipping (likely stryker sandbox)`);
      return;
    }
    const content = await readFile(file, 'utf8');
    const doc = parseYaml(content) as { transitions: Array<{ from: string; to: string; event: string; action_workflow: string }> };
    expect(doc.transitions).toBeDefined();
    expect(doc.transitions.length).toBeGreaterThan(5);

    // happy path must be present
    const happyPath = ['draft', 'scaffolded', 'tested', 'validated', 'released'];
    for (let i = 0; i < happyPath.length - 1; i++) {
      const found = doc.transitions.some(
        t => t.from === happyPath[i] && t.to === happyPath[i + 1],
      );
      expect(found, `transition ${happyPath[i]} → ${happyPath[i + 1]} must exist`).toBe(true);
    }

    // wildcard failure transition must be present
    const wildcard = doc.transitions.find(t => t.from === '*' && t.event === '*.failed');
    expect(wildcard).toBeDefined();
    expect(wildcard?.to).toBe('failed');
  });
});
