/**
 * CLI entry point — `mcp-builder` command.
 *
 * Subcomandos:
 *   mcp-builder new <name> [--sdk --pattern --tools]  # gera novo MCP
 *   mcp-builder serve                                 # inicia como MCP server
 *   mcp-builder serve:http [--port 3000]              # inicia HTTP API
 *   mcp-builder list-templates                        # lista templates disponíveis
 *   mcp-builder validate <spec.json>                  # valida spec
 *   mcp-builder fsm show                              # gera diagrama Mermaid do FSM
 *   mcp-builder fsm transition <from> <event>         # computa próxima transição
 */

import { Command } from 'commander';
import { readFile, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';
import { createLogger } from '../logger/index.js';
import { Scaffolder } from '../scaffolder/index.js';
import { FSM } from '../fsm/index.js';
import { validateMCPSpec } from '../validator/index.js';
import { startMCPServer } from '../mcp/server.js';
import { startHTTPServer } from '../http/server.js';
import { parseBlueprint, parseBlueprints, BlueprintParseError, BlueprintExecutor, hashBlueprint } from '../blueprint/index.js';
import type { MCPSpec, SDK, Pattern } from '../types.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

function findTemplatesRoot(): string {
  // Em dev: builder/src/cli → ../../../templates (sobe src, builder, cai em mcp-builder/templates)
  // Em prod: builder/dist/cli → ../../../templates (sobe dist, builder, cai em mcp-builder/templates)
  const candidates = [
    join(__dirname, '..', '..', '..', 'templates'),
    join(__dirname, '..', '..', 'templates'),
    join(__dirname, '..', 'templates'),
    join(process.cwd(), 'templates'),
  ];
  for (const c of candidates) {
    if (existsSync(c)) return c;
  }
  return candidates[0];
}

function findRepoRoot(): string {
  // Em dev: builder/src/cli → ../../.. (sobe src, builder, cai em mcp-builder)
  // Em prod: builder/dist/cli → ../../.. (sobe dist, builder, cai em mcp-builder)
  const candidates = [
    join(__dirname, '..', '..', '..'),
    join(__dirname, '..', '..'),
    process.cwd(),
  ];
  for (const c of candidates) {
    if (existsSync(join(c, '.mcp', 'state', 'states.yaml'))) return c;
  }
  return candidates[0];
}

export function createCLI(): Command {
  const program = new Command();
  const logger = createLogger();

  program
    .name('mcp-builder')
    .description('MCP Builder — generates, validates and operates MCP servers')
    .version('1.0.0')
    .option('-v, --verbose', 'verbose logging', false);

  // ==========================================================================
  // new
  // ==========================================================================
  program
    .command('new <name>')
    .description('scaffold a new MCP server project')
    .option('--sdk <sdk>', 'target SDK (python|typescript|go|rust)', 'python')
    .option('--pattern <pattern>', 'architectural pattern (event|factory|stateless)', 'stateless')
    .option('--tools <tools>', 'comma-separated tool names (snake_case)', '')
    .option('--output <dir>', 'output directory', './')
    .option('--skip-git', 'skip git init', false)
    .option('--skip-hooks', 'skip gate/advisor hooks (dev only)', false)
    .action(async (name: string, opts: {
      sdk: SDK;
      pattern: Pattern;
      tools: string;
      output: string;
      skipGit: boolean;
      skipHooks: boolean;
    }) => {
      const templatesRoot = findTemplatesRoot();
      const outputRoot = resolve(opts.output);

      const tools = opts.tools
        ? opts.tools.split(',').map(t => t.trim()).filter(Boolean)
        : ['default_tool'];

      const spec: MCPSpec = {
        name,
        description: `MCP server ${name} generated by mcp-builder`,
        sdk: opts.sdk,
        pattern: opts.pattern,
        tools: tools.map(t => ({
          name: t,
          description: `${t} tool for ${name}`,
          inputSchema: { type: 'object', properties: {} },
        })),
      };

      logger.info('scaffolding project', { name, sdk: opts.sdk, pattern: opts.pattern });

      const scaffolder = new Scaffolder({
        templatesRoot,
        outputRoot,
        skipGit: opts.skipGit,
      });

      const result = await scaffolder.generate(spec);
      if (!result.ok) {
        logger.error('scaffold failed', { error: result.error });
        process.exit(1);
      }

      logger.info('project created', {
        path: result.projectPath,
        files: result.files.length,
      });
      console.log(`\n✓ Project ${name} created at ${result.projectPath}`);
      console.log(`  ${result.files.length} files generated`);
      console.log(`\nNext steps:`);
      console.log(`  cd ${name}`);
      console.log(`  # follow README.md in the generated project`);
    });

  // ==========================================================================
  // serve (MCP server próprio)
  // ==========================================================================
  program
    .command('serve')
    .description('start MCP Builder as an MCP server (loadable by Claude Code, Cursor)')
    .action(async () => {
      await startMCPServer({ logger });
    });

  // ==========================================================================
  // serve:http
  // ==========================================================================
  program
    .command('serve:http')
    .description('start HTTP API server')
    .option('--port <port>', 'port', '3000')
    .option('--host <host>', 'host', '0.0.0.0')
    .action(async (opts: { port: string; host: string }) => {
      await startHTTPServer({
        port: parseInt(opts.port, 10),
        host: opts.host,
        logger,
      });
    });

  // ==========================================================================
  // list-templates
  // ==========================================================================
  program
    .command('list-templates')
    .description('list available templates')
    .action(async () => {
      const templatesRoot = findTemplatesRoot();
      if (!existsSync(templatesRoot)) {
        console.log('No templates directory found.');
        return;
      }
      const sdks = await readdir(templatesRoot);
      for (const sdk of sdks) {
        const sdkDir = join(templatesRoot, sdk);
        const patterns = (await readdir(sdkDir)).filter(async p => {
          const s = await stat(p);
          return s.isDirectory();
        });
        console.log(`\n${sdk}:`);
        for (const p of patterns) {
          console.log(`  - ${p}`);
        }
      }
    });

  // ==========================================================================
  // validate
  // ==========================================================================
  program
    .command('validate <spec.json>')
    .description('validate an MCPSpec JSON file')
    .action(async (specPath: string) => {
      const raw = await readFile(specPath, 'utf8');
      const spec = JSON.parse(raw);
      const result = validateMCPSpec(spec);
      if (result.ok) {
        console.log('✓ spec is valid');
      } else {
        console.log('✗ spec is invalid:');
        console.log(`  reason: ${result.block?.reason}`);
        for (const s of result.block?.suggestions ?? []) {
          console.log(`  suggestion: ${s}`);
        }
        process.exit(1);
      }
    });

  // ==========================================================================
  // fsm-show
  // ==========================================================================
  program
    .command('fsm-show')
    .description('show FSM as Mermaid state diagram')
    .action(async () => {
      const repoRoot = findRepoRoot();
      const fsm = await FSM.fromRepo(repoRoot);
      console.log(fsm.toMermaid());
    });

  // ==========================================================================
  // fsm-transition
  // ==========================================================================
  program
    .command('fsm-transition <from> <event>')
    .description('compute next transition')
    .action(async (from: string, event: string) => {
      const repoRoot = findRepoRoot();
      const fsm = await FSM.fromRepo(repoRoot);
      const ctx = { ...FSM.initialContext(), current: from };
      try {
        const t = fsm.transition(ctx, event);
        console.log(`${from} --(${event})--> ${t.to}  [workflow: ${t.action_workflow}]`);
      } catch (err) {
        console.log(`✗ no transition from ${from} on event ${event}`);
        process.exit(1);
      }
    });

  // ==========================================================================
  // blueprint validate
  // ==========================================================================
  program
    .command('blueprint-validate <path>')
    .description('validate a blueprint.yaml file (Devin-style)')
    .action(async (path: string) => {
      try {
        const { readFileSync } = await import('node:fs');
        const content = readFileSync(path, 'utf8');
        const bps = parseBlueprints(content);
        console.log(`✓ valid blueprint (${bps.length} document(s))`);
        for (const bp of bps) {
          console.log(`  - ${bp.name} [scope: ${bp.scope}]`);
          if (bp.initialize) console.log(`    initialize: ${Array.isArray(bp.initialize) ? bp.initialize.length : 1} step(s)`);
          if (bp.maintenance) console.log(`    maintenance: ${Array.isArray(bp.maintenance) ? bp.maintenance.length : 1} step(s)`);
          if (bp.knowledge) console.log(`    knowledge: ${bp.knowledge.length} entr(y|ies)`);
          if (bp.postBuild) console.log(`    post-build: ${Array.isArray(bp.postBuild) ? bp.postBuild.length : 1} step(s)`);
          if (bp.clone) console.log(`    clone: configured`);
          console.log(`    hash: ${hashBlueprint(bp).slice(0, 16)}`);
        }
      } catch (err) {
        if (err instanceof BlueprintParseError) {
          console.log(`✗ invalid blueprint: ${err.message}`);
        } else {
          console.log(`✗ error: ${(err as Error).message}`);
        }
        process.exit(1);
      }
    });

  // ==========================================================================
  // blueprint run
  // ==========================================================================
  program
    .command('blueprint-run <path>')
    .description('execute a blueprint.yaml locally (initialize + maintenance)')
    .option('--scope <scope>', 'blueprint scope (repository|organization|enterprise)', 'repository')
    .option('--workdir <dir>', 'working directory', process.cwd())
    .action(async (path: string, opts: { scope: 'repository' | 'organization' | 'enterprise'; workdir: string }) => {
      const { readFileSync } = await import('node:fs');
      const content = readFileSync(path, 'utf8');
      const bp = parseBlueprint(content, opts.scope);

      const ctx = BlueprintExecutor.createContext({
        scope: opts.scope,
        workdir: opts.workdir,
        logger: {
          info: (m, meta) => console.log(`[INFO] ${m}`, meta ? JSON.stringify(meta) : ''),
          warn: (m, meta) => console.warn(`[WARN] ${m}`, meta ? JSON.stringify(meta) : ''),
          error: (m, meta) => console.error(`[ERROR] ${m}`, meta ? JSON.stringify(meta) : ''),
        },
      });

      const executor = new BlueprintExecutor(ctx);
      const result = await executor.execute(bp);

      console.log('\n=== Blueprint execution result ===');
      console.log(`ok: ${result.ok}`);
      console.log(`steps: ${result.steps.length}`);
      console.log(`duration: ${result.durationMs}ms`);
      for (const step of result.steps) {
        const icon = step.ok ? '✓' : '✗';
        console.log(`  ${icon} ${step.name ?? '(unnamed)'} — ${step.durationMs}ms exit=${step.exitCode}`);
      }

      if (!result.ok) process.exit(1);
    });

  // ==========================================================================
  // blueprint knowledge
  // ==========================================================================
  program
    .command('blueprint-knowledge <path>')
    .description('extract knowledge entries from a blueprint (non-executed reference)')
    .action(async (path: string) => {
      const { readFileSync } = await import('node:fs');
      const content = readFileSync(path, 'utf8');
      const bp = parseBlueprint(content);

      const executor = new BlueprintExecutor(BlueprintExecutor.createContext({
        scope: 'repository',
        workdir: process.cwd(),
        logger: { info: () => {}, warn: () => {}, error: () => {} },
      }));
      const knowledge = executor.extractKnowledge(bp);

      if (knowledge.length === 0) {
        console.log('(no knowledge entries)');
        return;
      }

      for (const entry of knowledge) {
        console.log(`\n## ${entry.name}`);
        console.log(entry.contents);
      }
    });

  return program;
}

// stat helper local
async function stat(p: string) {
  return await import('node:fs/promises').then(m => m.stat(p));
}

// Run if invoked directly
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const program = createCLI();
  program.parseAsync(process.argv).catch(err => {
    console.error('fatal:', err);
    process.exit(1);
  });
}
